services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    deploy:
      resources:
        limits:
          cpus: '2.0'          # Limite de até 1.5 núcleos de CPU [2, 10]
          memory: 3048M        # Limite máximo de 1024 MB de RAM [2, 10]
        reservations:
          cpus: '0.5'          # Reserva garantida de 0.5 CPU
          memory: 256M         # Reserva garantida de 512 MB RAM [1]
    networks:
      - minha-rede

  webflux-postgres:
    image: postgres
    command: >
      postgres
      -c max_connections=300
      -c shared_buffers=256MB
      -c effective_cache_size=512MB
      -c work_mem=4MB
      -c maintenance_work_mem=64MB
    deploy:
      resources:
        limits:
          cpus: '2.0'          # Limite de até 1.5 núcleos de CPU [2, 10]
          memory: 1024M        # Limite máximo de 1024 MB de RAM [2, 10]
        reservations:
          cpus: '0.5'          # Reserva garantida de 0.5 CPU
          memory: 256M         # Reserva garantida de 512 MB RAM [1]
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "user@123"
      POSTGRES_DB: "api-performance"
    ports:
      - "5432:5432"
    networks:
      - minha-rede

  webflux-app:
    build:
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '1.5'          # Limite de até 1.5 núcleos de CPU [2, 10]
          memory: 3048M        # Limite máximo de 1024 MB de RAM [2, 10]
        reservations:
          cpus: '0.5'          # Reserva garantida de 0.5 CPU
          memory: 512M         # Reserva garantida de 512 MB RAM [1]
    ports:
      - "8080:8080"
    networks:
      - minha-rede
    depends_on:
      - webflux-postgres

networks:
  minha-rede: