spring:
  application:
    name: webflux-postgres-app

  security:
    auth:
      secret: teste
      issuer: teste

  r2dbc:
    url: r2dbc:postgresql://webflux-postgres:5432/api-performance
#    url: r2dbc:postgresql://localhost:5432/api-performance
    username: user
    password: user@123
    pool:
      initial-size: 10
      max-size: 30
      max-idle-time: 30m

  sql:
    init:
      mode: always

  main:
    web-application-type: reactive

server:
  port: 8080
  tomcat:
    threads:
      max: 10

logging:
  level:
    org.springframework: TRACE
    org.springframework.web: TRACE
    org.hibernate: TRACE
    root: TRACE

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
