spring:
  application:
    name: webflux-postgres-app
  security:
    auth:
      secret: teste
      issuer: teste

  r2dbc:
    url: r2dbc:postgresql://webflux-postgres:5432/api-performance
    username: user
    password: user@123

  sql:
    init:
      mode: always

  main:
    web-application-type: reactive

server:
  port: 8080
  tomcat:
    threads:
      max: 10

logging:
  level:
    org.springframework: ERROR
    org.springframework.web: ERROR
    org.hibernate: ERROR
    root: ERROR